FROM registry.centos.org/kbsingh/openshift-nginx:latest
MAINTAINER "Konrad Kleine <kkleine@redhat.com>"

ENV LANG=en_US.utf8

USER root
ADD nginx.conf /etc/nginx/nginx.conf

# Add the templater to run.sh
RUN sed -i '2s/^/\/template.sh \/usr\/share\/nginx\/html \n/' /run.sh

RUN rm /usr/share/nginx/html/*

ADD template.sh /

COPY dist /usr/share/nginx/html

RUN chown -R 997 /usr/share/nginx/html
USER 997
