= Fabric8 Planner

image:https://ci.centos.org/buildStatus/icon?job=devtools-fabric8-planner-build-master[Jenkins, link="https://ci.centos.org/view/Devtools/job/devtools-fabric8-planner-build-master/lastBuild/"]
image:https://ci.centos.org/buildStatus/icon?job=devtools-fabric8-planner-npm-publish-build-master[Jenkins, link="https://ci.centos.org/view/Devtools/job/devtools-fabric8-planner-npm-publish-build-master/lastBuild/"]
image:https://codecov.io/gh/fabric8-ui/fabric8-planner/branch/master/graph/badge.svg[Codecov.io, link="https://codecov.io/gh/fabric8-ui/fabric8-planner"]
image:https://img.shields.io/badge/%20%20%F0%9F%93%A6%F0%9F%9A%80-semantic%20release-b4d455.svg[Semantic Release, link="https://github.com/semantic-release/semantic-release"]

:icons:
:toc: macro
:toc-title:
:toclevels: 1

toc::[]

== Overview
Fabric8 Planner is a task planner and the issue tracker front-end for link:https://openshift.io/[openshift.io].
It uses the link:https://github.com/fabric8-services/fabric8-wit[Fabric8 Work Item Tracker] as the back-end.

The Planner project provides a component library which is used by other applications to provide a task planning front-end.

== Running the Planner

The Planner is available as an npm package. It can not be run by itself as it is an Angular component library.

However, for development and testing purpose, a minimal runtime environment is available in the xref:../runtime[*_runtime_*] directory. So you can run Planner either as a minimal Standalone component or as an Integrated component using an external webapp like the *_fabric8-ui_*. Typically, you would want to develop in the Standalone mode and test your changes in the Integrated mode.

=== Quickstart

The Planner build can be quickly run using the xref:../scripts/run-planner.sh[launcher script].

You can use the launcher script to run the Planner either as a Standalone component or as an Integrated component using an external webapp like the fabric8-ui.

- To run a minimal runtime implementation of the Planner using an in-memory mock database use:
+
----
$ scripts/run-planner.sh --standalone
----
You can access the service on *`localhost:8080`*

- To run the Planner in an integrated environment using an external webapp, use:
+
----
$ scripts/run-planner.sh
----
+
Note that the above command can be used out-of-the-box with the *_fabric8-ui_* project.

The paths for the runtimes can be configured using command line arguments.
See the xref:../scripts/run-planner.sh[launcher script] for further information.

NOTE: To run the script on macOS, install `gnu-getopt`, run `brew install gnu-getopt`, and set it in your PATH:
 `echo 'export PATH="/usr/local/opt/gnu-getopt/bin:$PATH"' >> ~/.zshrc`.

For information on running the build manually see xref:..docs/building_planner.adoc[Building the Planner Component Library] documentation.

== Other Useful Scripts and Tasks

The Planner uses `gulp` as the build tool and provides frequently used tasks like `npm` tasks as well.
The `scripts` section of the xref:../package.json [*_package.json_*] file lists all the tasks available.

The following table lists some of the most useful or frequently used scripts and `gulp` tasks you may need to run:

[cols="1,2,4", options="header"]
|===
|Script
|Command
|Description

|Clean
|`$ npm run clean:all`
|Cleans the project directory

|Reinstall
|`$ npm run reinstall`
|Cleans the dependencies and reinstalls them

|Unit Tests
|`$ npm run test:unit`
|Runs the unit tests

|Semantic Release
|`$ npm run semantic-release`
|Builds the library and performs a semantic release to npmjs

|Continuous Build
|`$ npm run watch:library`
|Runs the build in watch mode, watches for changes and rebuilds source
|===

== Documentation
The following documentation is available in the *_docs_* directory:

- xref:../docs/building_planner.adoc[Building the Planner]: Provides information on manually building the Planner in Standalone, Integrated, and Production environments.
- xref:../docs/technology_stack.adoc[Technology Stack]: Lists the the technology stack used by Planner.
- xref:../docs/testing.adoc[Testing]: Covers the tests you can run on Planner.

== Contributing

All contributions are welcome, if you want to contribute to this project, ensure you follow the xref:../CONTRIBUTING.adoc[Contribution Guidelines].
