= Fabric8 Planner

image:https://ci.centos.org/buildStatus/icon?job=devtools-fabric8-planner-build-master[Jenkins, link="https://ci.centos.org/view/Devtools/job/devtools-fabric8-planner-build-master/lastBuild/"]
image:https://ci.centos.org/buildStatus/icon?job=devtools-fabric8-planner-npm-publish-build-master[Jenkins, link="https://ci.centos.org/view/Devtools/job/devtools-fabric8-planner-npm-publish-build-master/lastBuild/"]
image:https://codecov.io/gh/fabric8io/fabric8-planner/branch/master/graph/badge.svg[Codecov.io, link="https://codecov.io/gh/fabric8io/fabric8-planner"]
image:https://img.shields.io/badge/%20%20%F0%9F%93%A6%F0%9F%9A%80-semantic%20release-b4d455.svg[Semantic Release, link="https://github.com/semantic-release/semantic-release"]

**Fabric8 Planner is a task planner and issue tracker front-end for openshift.io**

It uses https://github.com/almighty/almighty-core[Fabric8 Work Item Tracker]
as the back-end. The Planner project itself only provides a component library
is being used by other applications to provide a task planning frontend. For
testing and experimental use, a minimal runtime is part of the Planner repository.

== Running the Planner

The Planner can not be run by itself as it is an Angular component library. But 
for testing purposes, a minimal runtime implementation is provided in the `runtime` 
directory. To run the minimal runtime, follow the steps in *`runtime/README.adoc`*.

=== Quickstart 

To quickly run the provided minimal Runtime with the Planner, simply run

 $ scripts/run-planner.sh --standalone

> NOTE: To run the script on macOS, you will need to have `gnu-getopt` installed, run `brew install gnu-getopt`, and set it in your PATH
 `echo 'export PATH="/usr/local/opt/gnu-getopt/bin:$PATH"' >> ~/.zshrc`

This will run the Planner using the minimal Runtime and a mock database. The service 
will be available on *`localhost:8080`*

=== Running the Unit Tests

To run the linter, build validator, and unit tests use:

 $ gulp test:unit

== Other Useful Scripts and Tasks

The Planner uses `gulp` as the build tool and provides frequent used tasks as `npm` 
tasks as well. The *`package.json`* file's `scripts:` section lists all the tasks available. 

Here are some of the most useful/frequently used scripts and `gulp` tasks you may need to run:

[cols="1,2,4", options="header"]
|===
|Script
|Command
|Description

|Clean
|`$ npm run clean:all`
|Cleans the project directory

|Reinstall
|`$ npm run reinstall`
|Cleans the dependencies and reinstalls them

|Unit Tests
|`$ npm run test:unit`
|Runs the unit tests

|Semantic Release
|`$ npm run semantic-release`
|Builds the library and performs a semantic release to npmjs

|Continuous Build
|`$ npm run watch:library`
|Runs the build in watch mode, watching changes and rebuilding source
|===

== Building the Component Library

=== Production build

To generate production build, set API URL and run build script as follows:

----
$ npm run build
----

The created library will be placed in `dist`.

IMPORTANT: *You shouldn't ever publish the build manually,* instead you should
let the CD pipeline do a semantic release.

=== Development Build

To build fabric8-planner as an npm library and embed it into a webapp such as
fabric8-ui, you should:

Step 1: Run `npm run watch:library` in the source directory::
This will build fabric8-planner as a library and then set up a watch task to
rebuild any ts, html and scss files you change.

Step 2: Run `npm link <path to fabric8-planner>/dist-watch`::
In the webapp into which you are embedding. This will create a symlink from
`node_modules/fabric8-planner` to the `dist-watch` directory and install that
symlinked node module into your webapp.

Step 3: Run your webapp in development mode::
Make sure you have a watch on `node_modules/fabric8-planner` enabled. You will
have access to both JS and SASS sourcemaps if your webapp is properly setup.

NOTE: `fabric8-ui` is setup to do reloading and sourcemaps automatically when you
run `npm start`.

=== Development Build using the Launcher Script

The above integration can be run with the provided launcher script in `scripts/run-planner.sh`.

There are two options available when using the script:

1. Running the Planner using te standalone minimal Runtime and an inmemory mock database.
2. Running the Planner using an external Runtime that uses the procedure above for 
   integration (this can be used out-of-the-box with the `fabric8-ui? project)

Using the minimal Runtime and a mock database (option 1) run:

 $ scripts/run-planner.sh --standalone
 
Using an external Runtime (option 1) run:

 $ scripts/run-planner.sh 

The paths for the runtimes can be configured using commandline arguments. See 
`scripts/run-planner.sh` for further documentation.

== CSS and SASS

fabric8-planner uses SASS for it's stylesheets. It also uses the Angular emulation
of the shadow dom, so you will normally want to place your styles in the
`.component.scss` file next to the html and the typescript.

If you find yourself wanting to create a shared style that multiple components will
use, then we recommend adding it as a mixin to
`src/assets/stylesheets/_planner-mixins.scss`. The mixins are imported in to every
`.component.scss` file. You can then create a real class by doing something like

    .my-class {
      @include my-class;
    }

We use mixins to avoid polluting components with uncessary style classes, and to avoid
an explosion of shared files.

The `src/assets/stylesheets/` directory includes a `shared` directory. These are
shared global styles that we will refactor out in to a shared library at some point.
Only update these styles if you are making a truly global style, and are going to
synchronise your changes across all the various UI projects.

== Contributing to the app

The development guide is part of the link:./CONTRIBUTING.adoc[contributors'
instructions]. Please check it out in order to contribute to this project.
