= Minimal Standalone Runtime for the Planner

This is a minimal Runtime for the Planner component library. It provides a complete runtime
environment alongside a mock inmemory database to run functional tests or experiment with the
Planner library.

== Running The Project

To use this with the Planner library:

1. Get dependencies for Planner (in planner root directory): `npm install`
2. Get dependencies for Planner Runtime (in `runtime`): `npm install`
3. Start the library build in watch mode (in planner root directory): `npm run watch:library`
4. Link Planner library to runtime (in `runtime`): `npm link ../dist-watch`
5. Set runtime mode to inmemory (if applicable): `export NODE_ENV=inmemory`
6. Build and run runtime: (in `runtime`): `npm start`
7. Point your browser to http://localhost:8080/

== Functional Tests

* To run all the functional tests you can simply run (in `runtime`): `npm run test:func`
* To run only the **smoke** functional tests you can simply run (in `runtime`): `npm run test:funcsmoke`

== Building for Functional Tests or Standalone Production

1. Build Planner library (in planner root directory): `npm run build`
2. Link Planner library to runtime (in `runtime`): `npm link ../dist`
3. Build Runtime (in `runtime`): `npm run build`

The runtime is now available in runtime/dist.

== The `NODE_ENV` Variable

The `NODE_ENV` environment variable sets the execution environment on build time
for the provided minimal runtime.

If you're just trying to test the application, please use inmemory mode which
will load the app with mock data for you. If you, however, want to contribute
to the codebase, unset it back or to "development" (default) mode and rebuild.


[source,shell]
```
$ export NODE_ENV=inmemory # <1>
$ export NODE_ENV=development # <2>
$ export NODE_ENV=production # <3>

<1> In-memory mode for trying-out the app
<2> Development mode for contributing to the source
<2> Production mode for deploying the application
```

Once you're done setting the environment, you can proceed with the next step(s)

NOTE: If you're directly trying to run the app in dev mode, you can skip this
step, as *`NODE_ENV`* is treated as `"development"` by default.

IMPORTANT: If you're trying out the app `"inmemory"` mode, then after running
the app (as explained in the next step) please don't forget to
http://localhost:8088/?token_json=%7B%22access_token%22%3A%22somerandomtoken%22%2C%22expires_in%22%3A1800%2C%22refresh_expires_in%22%3A1800%2C%22refresh_token%22%3A%22somerandomtoken%22%2C%22token_type%22%3A%22bearer%22%7D[visit this URL]
to load it up with mock data, including the authenticated/logged-in user.

== Production build

To generate production build, set API URL and run build script as follows:

----
$ npm run build
----

The build output will be under `dist` directory.

*To create a docker image,* run this command immediately after the production
build completion:

----
$ docker build -t fabric8-planner-deploy -f Dockerfile.deploy .
----

== Run tests locally

To run the test like done in the CI, you should under the home repo directory.
Next, you just need to run the following command:

---
$ ./scripts/local_docker.sh
---

This script generates a docker image that you could use to run planner within a container.

Optionally, you could also run the functional tests by passing `functionalTests`
as argument to the following script:

---
$ ./scripts/local_docker.sh functionalTests
---
