const { FABRIC8_AUTH_API_URL, FABRIC8_FEATURE_TOGGLES_API_URL, FABRIC8_WIT_API_URL } = process.env;

const DEFAULT_URL = '/api/';

export const AUTH_API_URL = FABRIC8_AUTH_API_URL || DEFAULT_URL;
export const FEATURE_TOGGLES_API_URL = FABRIC8_FEATURE_TOGGLES_API_URL || DEFAULT_URL;
export const WIT_API_URL = FABRIC8_WIT_API_URL || DEFAULT_URL;
