export class Constants {
  browserName = {
    'browserSDD': {
      'areaTitle1': '/' + process.env.SPACE_NAME + '/Area_1',
      'areaTitle2': '/' + process.env.SPACE_NAME + '/Area_2',
      'childType': 'Experience',
      'commentCollaboratorTest' : 'Work Item 2',
      'dropdownareaTitle1': 'Area_1',
      'dropdownareaTitle2': 'Area_2',
      'dropdownIteration1': 'Iteration_1/Iteration1_1',
      'dropdownIteration_2': 'Iteration_2',
      'dropdownIteration2' : 'Iteration_1',
      'filterLabel': 'state: closed',
      'group1': 'Scenarios',
      'group2': 'Experiences',
      'group3': 'Requirements',
      'iteration1': '/' + process.env.SPACE_NAME + '/Iteration_1/Iteration1_1',
      'iteration2': '/' + process.env.SPACE_NAME + '/Iteration_2',
      'IterationTestTitle' : {
        'title': 'test list is not updated when new iteration is added',
        'type': 'Experience'
      },
      'rootIteration': '/' + process.env.SPACE_NAME,
      'newIteration': 'new Iteration',
      'newIteration1': 'new Iteration 1',
      'parentIteration': '/' + process.env.SPACE_NAME + '/Iteration_2',
      'searchWorkItem3': '2 - Workitem_Title_3',
      'searchWorkItem4': '3 - Workitem_Title_4',
      'type': ' Scenario',
      'stateOpen': 'open',
      'stateNew': 'new',
      'stateClosed': 'closed',
      'stateInProgress': 'in progress',
      'stateResolved': 'resolved',
      'typeIssue': 'Bug',
      'updateIteration' : 'Iteration_2123',
      'user1': process.env.USER_FULLNAME,
       // Required since we need 2 users. Do not remove
      'user2': process.env.USER_FULLNAME,
      'Workitem_Title_3': 'Workitem_Title_3',
      'Workitem_Title_4': 'Workitem_Title_4',
      'workItemTypeFilter' : 'workitemtype: Scenario',
      'workitem': { title : 'new detail workItem', type: 'Scenario'},
      'user_avatar': 'https://www.gravatar.com/avatar/f56b4884b4041f14b13d919008fd7d44.jpg&s=25'
    },
    'browserAgile': {
      'areaTitle1': '/' + process.env.SPACE_NAME_SCRUM + '/Area_6',
      'areaTitle2': '/' + process.env.SPACE_NAME_SCRUM + '/Area_7',
      'childType': 'Epic',
      'commentCollaboratorTest' : 'Work Item 1',
      'dropdownareaTitle1': 'Area_6',
      'dropdownareaTitle2': 'Area_7',
      'dropdownIteration1': 'Iteration_1/Iteration1_1',
      'dropdownIteration_2': 'Iteration_2',
      'dropdownIteration2' : 'Iteration_1',
      'filterLabel': 'state: Closed',
      'group1': 'Work Items',
      'group2': 'Work Items',
      'group3': 'Work Items',
      'iteration1': '/' + process.env.SPACE_NAME_SCRUM + '/Iteration_1/Iteration1_1',
      'iteration2': '/' + process.env.SPACE_NAME_SCRUM + '/Iteration_2',
      'newIteration': 'new Iteration',
      'newIteration1': 'new Iteration 1',
      'parentIteration': '/' + process.env.SPACE_NAME_SCRUM + '/Iteration_2',
      'rootIteration': '/' + process.env.SPACE_NAME_SCRUM,
      'searchWorkItem3': '3 - Workitem_Title_3',
      'searchWorkItem4': '4 - Workitem_Title_4',
      'stateOpen': 'Open',
      'stateNew': 'New',
      'stateClosed': 'Closed',
      'stateInProgress': 'In Progress',
      'stateResolved': 'Resolved',
      'type': ' Defect',
      'typeIssue': 'Defect',
      // Required since we need 2 users. Do not remove
      'user2': process.env.USER_FULLNAME,
      'Workitem_Title_4': 'Workitem_Title_4',
      'Workitem_Title_3': 'Workitem_Title_3',
      'workitem': { title : 'new detail workItem', type: 'Task'},
      'workItemTypeFilter' : 'workitemtype: Defect',
      'user_avatar': 'https://www.gravatar.com/avatar/f56b4884b4041f14b13d919008fd7d44.jpg&s=25'
    }
  };
}
