export { SpaceNamespace } from './kubernetes/model/space-namespace';
export { EnvironmentListPageComponent } from './kubernetes/ui/environment/list-page/list-page.environment.component';
export { EnvironmentModule } from './kubernetes/ui/environment/environment.module';
export { AppModule } from './kubernetes/ui/app/app.module';
export { PipelineStatusComponent } from './kubernetes/components/pipeline-status/pipeline-status.component';
export { PodPhaseIconComponent } from './kubernetes/components/pod-phase-icon/pod-phase-icon.component';
export { KubernetesLabelsComponent } from './kubernetes/components/k8s-labels/k8s-labels.component';
export { BuildStatusIconComponent } from './kubernetes/components/build-status-icon/build-status-icon.component';
export { KubernetesComponentsModule } from './kubernetes/components/components.module';
export { Space, Environment, Spaces, asSpaces } from './kubernetes/model/space.model';
export { Service, Services, enrichServiceWithRoute } from './kubernetes/model/service.model';
export { ScalableResource } from './kubernetes/model/scalableresource.model';
export { Routes } from '@angular/router';
export { Route } from './kubernetes/model/route.model';
export { ReplicationController, ReplicationControllers } from './kubernetes/model/replicationcontroller.model';
export { ReplicaSet, ReplicaSets } from './kubernetes/model/replicaset.model';
export { Pod, Pods } from './kubernetes/model/pod.model';
export { PipelineStage } from './kubernetes/model/pipelinestage.model';
export { Namespace, Namespaces, isSecretsNamespace, isSystemNamespace } from './kubernetes/model/namespace.model';
export { KubernetesResource } from './kubernetes/model/kubernetesresource.model';
export { KubernetesSpecResource } from './kubernetes/model/kuberentesspecresource.model';
export { resourceKindToCollectionName, isNamespacedKind } from './kubernetes/model/helpers';
export { Events } from './kubernetes/model/event.model';
export { DeploymentConfig, DeploymentConfigs } from './kubernetes/model/deploymentconfig.model';
export { Deployment, Deployments } from './kubernetes/model/deployment.model';
export { ConfigMap, ConfigMaps } from './kubernetes/model/configmap.model';
export { Build, Builds } from './kubernetes/model/build.model';
export { KubernetesStoreModule } from './kubernetes/kubernetes.store.module';
export { SpaceModule } from './kubernetes/ui/space/space.module';
export { PipelineModule } from './kubernetes/ui/pipeline/pipeline.module';
export { SpacesListComponent } from './kubernetes/ui/space/list/list.space.component';
export { KubernetesRestangularModule } from './kubernetes/service/kubernetes.restangular';
export {
  BuildConfig,
  BuildConfigs,
  combineBuildConfigAndBuilds,
  filterPipelines,
  findBuildConfigByID
} from './kubernetes/model/buildconfig.model';
export { BuildConfigStore } from './kubernetes/store/buildconfig.store';
export { BuildStore } from './kubernetes/store/build.store';
export { OnLogin } from './shared/onlogin.service';
export { FABRIC8_FORGE_API_URL } from './shared/fabric8-forge-api';
export { OAuthConfigStore } from './kubernetes/store/oauth-config-store';
export { APIsStore } from './kubernetes/store/apis.store';
export { LoginService } from './shared/login.service';
export { NamespaceScope } from './kubernetes/service/namespace.scope';
export { DevNamespaceScope } from './kubernetes/service/devnamespace.scope';
export { DeploymentModule } from './kubernetes/ui/deployment/deployment.module';
export { createDeploymentViews } from './kubernetes/view/deployment.view';
export { CompositeDeploymentStore } from './kubernetes/store/compositedeployment.store';
export { ServiceStore } from './kubernetes/store/service.store';
export { ServiceService } from './kubernetes/service/service.service';
export { DeploymentService } from './kubernetes/service/deployment.service';
export { DeploymentStore } from './kubernetes/store/deployment.store';
export { EventService } from './kubernetes/service/event.service';
export { EventStore } from './kubernetes/store/event.store';
export { PodService } from './kubernetes/service/pod.service';
export { PodStore } from './kubernetes/store/pod.store';
export { NamespaceService } from './kubernetes/service/namespace.service';
export { NamespaceStore } from './kubernetes/store/namespace.store';
export { ReplicaSetService } from './kubernetes/service/replicaset.service';
export { ReplicaSetStore } from './kubernetes/store/replicaset.store';
export { ReplicationControllerService } from './kubernetes/service/replicationcontroller.service';
export { ReplicationControllerStore } from './kubernetes/store/replicationcontroller.store';
export { ConfigMapService } from './kubernetes/service/configmap.service';
export { ConfigMapStore } from './kubernetes/store/configmap.store';
export { BuildConfigService } from './kubernetes/service/buildconfig.service';
export { DeploymentConfigService } from './kubernetes/service/deploymentconfig.service';
export { DeploymentConfigStore } from './kubernetes/store/deploymentconfig.store';
export { BuildService } from './kubernetes/service/build.service';
export { SpaceStore } from './kubernetes/store/space.store';
export { OAuthService } from 'angular2-oauth2/oauth-service';
export { RouteServiceStore } from './kubernetes/store/route.service.store';
export { RouteService } from './kubernetes/service/route.service';
export { RouteStore } from './kubernetes/store/route.store';
export { StatusListModule } from './kubernetes/ui/status/status-list.module';

export { DeploymentViews } from './kubernetes/view/deployment.view';
export { DeploymentView } from './kubernetes/view/deployment.view';
export { AppEnvironmentDetails, AppDeployments, EnvironmentDeployments } from './kubernetes/ui/app/list-page/list-page.app.component';
export { AbstractWatchComponent } from './kubernetes/support/abstract-watch.component';
